spring.application.name=MagicFridgeAI

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações locais corrigidas para o banco em memória H2
spring.datasource.url=jdbc:h2:mem:magicfridgedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA // HIBERNATE
# Alterado de validate para update para criar a tabela FOOD_ITEM automaticamente se não existir!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true